version: '3'
services:
  nuls-wallet-node1:
    build: .
    ports:
    - 8001:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.11
    volumes:
    - "./modules.ini:/nuls/conf/modules.ini"
    - "./node3/data:/nuls/data"
    - "./node3/logs:/nuls/logs"

  nuls-wallet-node2:
    build: .
    ports:
    - 8012:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.12
    volumes:
      - "./modules.ini:/nuls/conf/modules.ini"
      - "./node1/data:/nuls/data"
      - "./node1/logs:/nuls/logs"

  nuls-wallet-node3:
    build: .
    ports:
    - 8013:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.13
    volumes:
    - "./modules.ini:/nuls/conf/modules.ini"
    - "./node2/data:/nuls/data"
    - "./node2/logs:/nuls/logs"

  nuls-wallet-node4:
    build: .
    ports:
    - 8014:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.14
    volumes:
    - "./modules.ini:/nuls/conf/modules.ini"
    - "./node4/data:/nuls/data"
    - "./node4/logs:/nuls/logs"

  nuls-wallet-node5:
    build: .
    ports:
    - 8015:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.15
    volumes:
    - "./modules.ini:/nuls/conf/modules.ini"
    - "./node5/data:/nuls/data"
    - "./node5/logs:/nuls/logs"

networks:
  overlay:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24