version: '3'
services:
  nuls-wallet:
    build: .
    ports:
    - 127.0.0.1:8001:8001
    - 8003:8003
    volumes:
    - "./standalone/data:/nuls/data"
    - "./standalone/logs:/nuls/logs"
    - "./conf/modules.ini:/nuls/conf/modules.ini"
    - "./conf/nuls-version.xml:/nuls/conf/nuls-version.xml"
    - "./conf/block/genesis-block.json:/nuls/conf/block/genesis-block.json"
