version: '3'
services:
  nuls-wallet-node1:
    build: .
    ports:
    - 8001:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.11
    volumes:
    - "./private/node1/data:/nuls/data"
    - "./private/node1/logs:/nuls/logs"
    - "./conf/modules.ini:/nuls/conf/modules.ini"
    - "./conf/block/genesis-block.json:/nuls/conf/block/genesis-block.json"

  nuls-wallet-node2:
    build: .
    ports:
    - 8012:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.12
    volumes:
    - "./private/node2/data:/nuls/data"
    - "./private/node2/logs:/nuls/logs"
    - "./conf/modules.ini:/nuls/conf/modules.ini"
    - "./conf/block/genesis-block.json:/nuls/conf/block/genesis-block.json"

  nuls-wallet-node3:
    build: .
    ports:
    - 8013:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.13
    volumes:
    - "./private/node3/data:/nuls/data"
    - "./private/node3/logs:/nuls/logs"
    - "./conf/modules.ini:/nuls/conf/modules.ini"
    - "./conf/block/genesis-block.json:/nuls/conf/block/genesis-block.json"

  nuls-wallet-node4:
    build: .
    ports:
    - 8014:8001
    networks:
      overlay:
        ipv4_address: 172.16.0.14
    volumes:
    - "./private/node4/data:/nuls/data"
    - "./private/node4/logs:/nuls/logs"
    - "./conf/modules.ini:/nuls/conf/modules.ini"
    - "./conf/block/genesis-block.json:/nuls/conf/block/genesis-block.json"

networks:
  overlay:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24